kubeconfig: "~/.kube/config"
namespace: "argocd"

argocd_repo_url: "https://github.com/argoproj/argocd-example-apps"

argocd_admin_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37633463623461366632316664613661396132373239626666623736303865653535366439633634
          6433363738653233646432666136353230383131326663620a363463656431383063373035306337
          61396239646538336264386431336364343436376163623130313663323634333961626363616261
          3636396336633961390a366534306235376237393138633433666261643930623734323032353766
          36613162666334646266303262653737393966653565656162613835613937313933

demo_deployer_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35643932393334633738386365303632326262646131333737323963366462383130306564646633
          6436663339626464333136316132356465376331363635300a313734633330303138656338313664
          31663038376366356265323432363531613064336338396333363630656139396361653239306137
          6166373264626161660a393638373938616439373137663062643437316262316133333161346464
          32616363396463376463383832373263373062313261363334613730666539633466

readonly_user_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33323266353536333836636565633363346666646535366166393665636637323431393231376639
          6563306262323162313132353263666636313736316264360a353563316230616263636365333537
          63386632326334383432626138356532393165653737616465343061626363613333376231623165
          3261316536646333300a313465646131343465353434363264613837326530336561333663343237
          66623263646536346438396463633564356633363663373031613731333962666532
